/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './video.player.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './video.player.component';
const styles_VideoPlayerComponent:any[] = [import0.styles];
export const RenderType_VideoPlayerComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_VideoPlayerComponent,
  data: {}
}
);
export function View_VideoPlayerComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,([] as any[]),(null as any),(null as any));
}
function View_VideoPlayerComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'video-player',([] as any[]),(null as any),(null as any),(null as any),View_VideoPlayerComponent_0,RenderType_VideoPlayerComponent)),
    import1.ɵdid(114688,(null as any),0,import2.VideoPlayerComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const VideoPlayerComponentNgFactory:import1.ComponentFactory<import2.VideoPlayerComponent> = import1.ɵccf('video-player',import2.VideoPlayerComponent,View_VideoPlayerComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2Fib3gvd29ya3NwYWNlL3NyYy93ZWIvd3d3cm9vdC9hcHAvY29tcG9uZW50cy92aWRlby1wbGF5ZXIvdmlkZW8ucGxheWVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2NhYm94L3dvcmtzcGFjZS9zcmMvd2ViL3d3d3Jvb3QvYXBwL2NvbXBvbmVudHMvdmlkZW8tcGxheWVyL3ZpZGVvLnBsYXllci5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL2NhYm94L3dvcmtzcGFjZS9zcmMvd2ViL3d3d3Jvb3QvYXBwL2NvbXBvbmVudHMvdmlkZW8tcGxheWVyL3ZpZGVvLnBsYXllci5jb21wb25lbnQudHMuVmlkZW9QbGF5ZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8dmlkZW8tcGxheWVyPjwvdmlkZW8tcGxheWVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7Z0JBQUE7OztJQUFBOzs7In0=
