/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.server.module';
import * as import2 from '@angular/http';
import * as import3 from '@angular/common';
import * as import4 from '@angular/platform-browser';
import * as import5 from '@angular/platform-browser/animations';
import * as import6 from '@angular/platform-server';
import * as import7 from '@angular/forms';
import * as import8 from './app.module';
import * as import9 from '@angular/animations/browser';
import * as import10 from './app.component.ngfactory';
class AppServerModuleInjector extends import0.ɵNgModuleInjector<import1.AppServerModule> {
  _HttpModule_0:import2.HttpModule;
  _CommonModule_1:import3.CommonModule;
  _ErrorHandler_2:any;
  _APP_ID_3:any;
  _ɵTRANSITION_ID_4:any;
  _APP_INITIALIZER_5:any[];
  _ApplicationInitStatus_6:import0.ApplicationInitStatus;
  _ɵf_7:import0.ɵf;
  _ApplicationRef_8:any;
  _ApplicationModule_9:import0.ApplicationModule;
  _BrowserModule_10:import4.BrowserModule;
  _NoopAnimationsModule_11:import5.NoopAnimationsModule;
  _ServerModule_12:import6.ServerModule;
  _ɵba_13:import7.ɵba;
  _FormsModule_14:import7.FormsModule;
  _AppModule_15:import8.AppModule;
  _AppServerModule_16:import1.AppServerModule;
  __BrowserXhr_17:import6.ɵc;
  __ResponseOptions_18:import2.BaseResponseOptions;
  __XSRFStrategy_19:import6.ɵd;
  __XHRBackend_20:import2.XHRBackend;
  __RequestOptions_21:import2.BaseRequestOptions;
  __Http_22:any;
  __LOCALE_ID_23:any;
  __NgLocalization_24:import3.NgLocaleLocalization;
  __Compiler_25:import0.Compiler;
  __IterableDiffers_26:any;
  __KeyValueDiffers_27:any;
  __DomSanitizer_28:import4.ɵe;
  __Sanitizer_29:any;
  __HAMMER_GESTURE_CONFIG_30:import4.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_31:any[];
  __EventManager_32:import4.EventManager;
  __ɵDomSharedStylesHost_33:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_34:import4.ɵDomRendererFactory2;
  __ɵb_35:import6.ɵb;
  __ɵSharedStylesHost_36:any;
  __ɵServerRendererFactory2_37:import6.ɵServerRendererFactory2;
  __ɵAnimationEngine_38:import9.ɵNoopAnimationEngine;
  __RendererFactory2_39:any;
  __Testability_40:any;
  __Meta_41:import4.Meta;
  __Title_42:import4.Title;
  __ɵi_43:import7.ɵi;
  constructor(parent:import0.Injector) {
    super(parent,[import10.AppComponentNgFactory],[import10.AppComponentNgFactory]);
  }
  get _BrowserXhr_17():import6.ɵc {
    if ((this.__BrowserXhr_17 == null)) { (this.__BrowserXhr_17 = new import6.ɵc()); }
    return this.__BrowserXhr_17;
  }
  get _ResponseOptions_18():import2.BaseResponseOptions {
    if ((this.__ResponseOptions_18 == null)) { (this.__ResponseOptions_18 = new import2.BaseResponseOptions()); }
    return this.__ResponseOptions_18;
  }
  get _XSRFStrategy_19():import6.ɵd {
    if ((this.__XSRFStrategy_19 == null)) { (this.__XSRFStrategy_19 = new import6.ɵd()); }
    return this.__XSRFStrategy_19;
  }
  get _XHRBackend_20():import2.XHRBackend {
    if ((this.__XHRBackend_20 == null)) { (this.__XHRBackend_20 = new import2.XHRBackend(this._BrowserXhr_17,this._ResponseOptions_18,this._XSRFStrategy_19)); }
    return this.__XHRBackend_20;
  }
  get _RequestOptions_21():import2.BaseRequestOptions {
    if ((this.__RequestOptions_21 == null)) { (this.__RequestOptions_21 = new import2.BaseRequestOptions()); }
    return this.__RequestOptions_21;
  }
  get _Http_22():any {
    if ((this.__Http_22 == null)) { (this.__Http_22 = import6.ɵe(this._XHRBackend_20,this._RequestOptions_21)); }
    return this.__Http_22;
  }
  get _LOCALE_ID_23():any {
    if ((this.__LOCALE_ID_23 == null)) { (this.__LOCALE_ID_23 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_23;
  }
  get _NgLocalization_24():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_24 == null)) { (this.__NgLocalization_24 = new import3.NgLocaleLocalization(this._LOCALE_ID_23)); }
    return this.__NgLocalization_24;
  }
  get _Compiler_25():import0.Compiler {
    if ((this.__Compiler_25 == null)) { (this.__Compiler_25 = new import0.Compiler()); }
    return this.__Compiler_25;
  }
  get _IterableDiffers_26():any {
    if ((this.__IterableDiffers_26 == null)) { (this.__IterableDiffers_26 = import0.ɵl()); }
    return this.__IterableDiffers_26;
  }
  get _KeyValueDiffers_27():any {
    if ((this.__KeyValueDiffers_27 == null)) { (this.__KeyValueDiffers_27 = import0.ɵm()); }
    return this.__KeyValueDiffers_27;
  }
  get _DomSanitizer_28():import4.ɵe {
    if ((this.__DomSanitizer_28 == null)) { (this.__DomSanitizer_28 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_28;
  }
  get _Sanitizer_29():any {
    if ((this.__Sanitizer_29 == null)) { (this.__Sanitizer_29 = this._DomSanitizer_28); }
    return this.__Sanitizer_29;
  }
  get _HAMMER_GESTURE_CONFIG_30():import4.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_30 == null)) { (this.__HAMMER_GESTURE_CONFIG_30 = new import4.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_30;
  }
  get _EVENT_MANAGER_PLUGINS_31():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_31 == null)) { (this.__EVENT_MANAGER_PLUGINS_31 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_30)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_31;
  }
  get _EventManager_32():import4.EventManager {
    if ((this.__EventManager_32 == null)) { (this.__EventManager_32 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_31,this.parent.get(import0.NgZone))); }
    return this.__EventManager_32;
  }
  get _ɵDomSharedStylesHost_33():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_33 == null)) { (this.__ɵDomSharedStylesHost_33 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_33;
  }
  get _ɵDomRendererFactory2_34():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_34 == null)) { (this.__ɵDomRendererFactory2_34 = new import4.ɵDomRendererFactory2(this._EventManager_32,this._ɵDomSharedStylesHost_33)); }
    return this.__ɵDomRendererFactory2_34;
  }
  get _ɵb_35():import6.ɵb {
    if ((this.__ɵb_35 == null)) { (this.__ɵb_35 = new import6.ɵb(this.parent.get(import4.DOCUMENT),this._ɵTRANSITION_ID_4)); }
    return this.__ɵb_35;
  }
  get _ɵSharedStylesHost_36():any {
    if ((this.__ɵSharedStylesHost_36 == null)) { (this.__ɵSharedStylesHost_36 = this._ɵb_35); }
    return this.__ɵSharedStylesHost_36;
  }
  get _ɵServerRendererFactory2_37():import6.ɵServerRendererFactory2 {
    if ((this.__ɵServerRendererFactory2_37 == null)) { (this.__ɵServerRendererFactory2_37 = new import6.ɵServerRendererFactory2(this.parent.get(import0.NgZone),this.parent.get(import4.DOCUMENT),this._ɵSharedStylesHost_36)); }
    return this.__ɵServerRendererFactory2_37;
  }
  get _ɵAnimationEngine_38():import9.ɵNoopAnimationEngine {
    if ((this.__ɵAnimationEngine_38 == null)) { (this.__ɵAnimationEngine_38 = new import9.ɵNoopAnimationEngine()); }
    return this.__ɵAnimationEngine_38;
  }
  get _RendererFactory2_39():any {
    if ((this.__RendererFactory2_39 == null)) { (this.__RendererFactory2_39 = import6.ɵa(this._ɵServerRendererFactory2_37,this._ɵAnimationEngine_38,this.parent.get(import0.NgZone))); }
    return this.__RendererFactory2_39;
  }
  get _Testability_40():any {
    if ((this.__Testability_40 == null)) { (this.__Testability_40 = (null as any)); }
    return this.__Testability_40;
  }
  get _Meta_41():import4.Meta {
    if ((this.__Meta_41 == null)) { (this.__Meta_41 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_41;
  }
  get _Title_42():import4.Title {
    if ((this.__Title_42 == null)) { (this.__Title_42 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_42;
  }
  get _ɵi_43():import7.ɵi {
    if ((this.__ɵi_43 == null)) { (this.__ɵi_43 = new import7.ɵi()); }
    return this.__ɵi_43;
  }
  createInternal():import1.AppServerModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._CommonModule_1 = new import3.CommonModule();
    this._ErrorHandler_2 = import4.ɵa();
    this._APP_ID_3 = 'go-sammy';
    this._ɵTRANSITION_ID_4 = this._APP_ID_3;
    this._APP_INITIALIZER_5 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this.parent.get(import0.NgProbeToken,(null as any))),
      import4.ɵf(this._ɵTRANSITION_ID_4,this.parent.get(import4.DOCUMENT),this)
    ]
    ;
    this._ApplicationInitStatus_6 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_5);
    this._ɵf_7 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_2,this.componentFactoryResolver,this._ApplicationInitStatus_6);
    this._ApplicationRef_8 = this._ɵf_7;
    this._ApplicationModule_9 = new import0.ApplicationModule(this._ApplicationRef_8);
    this._BrowserModule_10 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._NoopAnimationsModule_11 = new import5.NoopAnimationsModule();
    this._ServerModule_12 = new import6.ServerModule();
    this._ɵba_13 = new import7.ɵba();
    this._FormsModule_14 = new import7.FormsModule();
    this._AppModule_15 = new import8.AppModule();
    this._AppServerModule_16 = new import1.AppServerModule();
    return this._AppServerModule_16;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import3.CommonModule)) { return this._CommonModule_1; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_2; }
    if ((token === import0.APP_ID)) { return this._APP_ID_3; }
    if ((token === import4.ɵTRANSITION_ID)) { return this._ɵTRANSITION_ID_4; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_5; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_6; }
    if ((token === import0.ɵf)) { return this._ɵf_7; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_8; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_9; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_10; }
    if ((token === import5.NoopAnimationsModule)) { return this._NoopAnimationsModule_11; }
    if ((token === import6.ServerModule)) { return this._ServerModule_12; }
    if ((token === import7.ɵba)) { return this._ɵba_13; }
    if ((token === import7.FormsModule)) { return this._FormsModule_14; }
    if ((token === import8.AppModule)) { return this._AppModule_15; }
    if ((token === import1.AppServerModule)) { return this._AppServerModule_16; }
    if ((token === import2.BrowserXhr)) { return this._BrowserXhr_17; }
    if ((token === import2.ResponseOptions)) { return this._ResponseOptions_18; }
    if ((token === import2.XSRFStrategy)) { return this._XSRFStrategy_19; }
    if ((token === import2.XHRBackend)) { return this._XHRBackend_20; }
    if ((token === import2.RequestOptions)) { return this._RequestOptions_21; }
    if ((token === import2.Http)) { return this._Http_22; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_23; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_24; }
    if ((token === import0.Compiler)) { return this._Compiler_25; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_26; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_27; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_28; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_29; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_30; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_31; }
    if ((token === import4.EventManager)) { return this._EventManager_32; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_33; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_34; }
    if ((token === import6.ɵb)) { return this._ɵb_35; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_36; }
    if ((token === import6.ɵServerRendererFactory2)) { return this._ɵServerRendererFactory2_37; }
    if ((token === import9.ɵAnimationEngine)) { return this._ɵAnimationEngine_38; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_39; }
    if ((token === import0.Testability)) { return this._Testability_40; }
    if ((token === import4.Meta)) { return this._Meta_41; }
    if ((token === import4.Title)) { return this._Title_42; }
    if ((token === import7.ɵi)) { return this._ɵi_43; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_7.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_33 && this._ɵDomSharedStylesHost_33.ngOnDestroy());
  }
}
export const AppServerModuleNgFactory:import0.NgModuleFactory<import1.AppServerModule> = new import0.NgModuleFactory<any>(AppServerModuleInjector,import1.AppServerModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2Fib3gvd29ya3NwYWNlL3NyYy93ZWIvd3d3cm9vdC9hcHAvYXBwLnNlcnZlci5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9jYWJveC93b3Jrc3BhY2Uvc3JjL3dlYi93d3dyb290L2FwcC9hcHAuc2VydmVyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
